channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.3
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
